// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "entity.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace procamPRL {

namespace {

const ::google::protobuf::Descriptor* Entity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Entity_reflection_ = NULL;
const ::google::protobuf::Descriptor* Entity_Image_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Entity_Image_reflection_ = NULL;
const ::google::protobuf::Descriptor* EntityList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EntityList_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* EntityList_Command_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_entity_2eproto() {
  protobuf_AddDesc_entity_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "entity.proto");
  GOOGLE_CHECK(file != NULL);
  Entity_descriptor_ = file->message_type(0);
  static const int Entity_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, pose_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, boundingsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, contours_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, projpixelsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, image_),
  };
  Entity_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Entity_descriptor_,
      Entity::default_instance_,
      Entity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Entity));
  Entity_Image_descriptor_ = Entity_descriptor_->nested_type(0);
  static const int Entity_Image_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity_Image, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity_Image, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity_Image, rgbpixelsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity_Image, data_),
  };
  Entity_Image_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Entity_Image_descriptor_,
      Entity_Image::default_instance_,
      Entity_Image_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity_Image, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Entity_Image, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Entity_Image));
  EntityList_descriptor_ = file->message_type(1);
  static const int EntityList_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EntityList, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EntityList, frameid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EntityList, command_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EntityList, entitylist_),
  };
  EntityList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      EntityList_descriptor_,
      EntityList::default_instance_,
      EntityList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EntityList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EntityList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(EntityList));
  EntityList_Command_descriptor_ = EntityList_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_entity_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Entity_descriptor_, &Entity::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Entity_Image_descriptor_, &Entity_Image::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    EntityList_descriptor_, &EntityList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_entity_2eproto() {
  delete Entity::default_instance_;
  delete Entity_reflection_;
  delete Entity_Image::default_instance_;
  delete Entity_Image_reflection_;
  delete EntityList::default_instance_;
  delete EntityList_reflection_;
}

void protobuf_AddDesc_entity_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::personalRobotics::protobuf_AddDesc_pose2D_2eproto();
  ::personalRobotics::protobuf_AddDesc_point2D_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014entity.proto\022\tprocamPRL\032\014pose2D.proto\032"
    "\rpoint2D.proto\"\333\002\n\006Entity\022&\n\004pose\030\001 \001(\0132"
    "\030.personalRobotics.Pose2D\022/\n\014boundingSiz"
    "e\030\002 \001(\0132\031.personalRobotics.Point2D\022\n\n\002id"
    "\030\003 \001(\005\022+\n\010contours\030\004 \003(\0132\031.personalRobot"
    "ics.Point2D\0220\n\rprojPixelSize\030\005 \001(\0132\031.per"
    "sonalRobotics.Point2D\022&\n\005image\030\006 \001(\0132\027.p"
    "rocamPRL.Entity.Image\032e\n\005Image\022\r\n\005width\030"
    "\001 \001(\005\022\016\n\006height\030\002 \001(\005\022/\n\014rgbPixelSize\030\003 "
    "\001(\0132\031.personalRobotics.Point2D\022\014\n\004data\030\004"
    " \001(\014\"\245\002\n\nEntityList\022\021\n\ttimestamp\030\001 \001(\001\022\017"
    "\n\007frameId\030\002 \001(\005\0224\n\007command\030\005 \001(\0162\035.proca"
    "mPRL.EntityList.Command:\004NONE\022%\n\nentityL"
    "ist\030\006 \003(\0132\021.procamPRL.Entity\"\225\001\n\007Command"
    "\022\010\n\004NONE\020\001\022\034\n\030SEND_DISPLAY_INFO_PACKET\020\002"
    "\022\025\n\021START_CALIBRATION\020\003\022\030\n\024CALIBRATION_C"
    "OMPLETE\020\004\022\020\n\014START_STREAM\020\005\022\017\n\013STOP_STRE"
    "AM\020\006\022\016\n\nDISCONNECT\020\007", 700);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "entity.proto", &protobuf_RegisterTypes);
  Entity::default_instance_ = new Entity();
  Entity_Image::default_instance_ = new Entity_Image();
  EntityList::default_instance_ = new EntityList();
  Entity::default_instance_->InitAsDefaultInstance();
  Entity_Image::default_instance_->InitAsDefaultInstance();
  EntityList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_entity_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_entity_2eproto {
  StaticDescriptorInitializer_entity_2eproto() {
    protobuf_AddDesc_entity_2eproto();
  }
} static_descriptor_initializer_entity_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Entity_Image::kWidthFieldNumber;
const int Entity_Image::kHeightFieldNumber;
const int Entity_Image::kRgbPixelSizeFieldNumber;
const int Entity_Image::kDataFieldNumber;
#endif  // !_MSC_VER

Entity_Image::Entity_Image()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:procamPRL.Entity.Image)
}

void Entity_Image::InitAsDefaultInstance() {
  rgbpixelsize_ = const_cast< ::personalRobotics::Point2D*>(&::personalRobotics::Point2D::default_instance());
}

Entity_Image::Entity_Image(const Entity_Image& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:procamPRL.Entity.Image)
}

void Entity_Image::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  width_ = 0;
  height_ = 0;
  rgbpixelsize_ = NULL;
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Entity_Image::~Entity_Image() {
  // @@protoc_insertion_point(destructor:procamPRL.Entity.Image)
  SharedDtor();
}

void Entity_Image::SharedDtor() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (this != default_instance_) {
    delete rgbpixelsize_;
  }
}

void Entity_Image::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Entity_Image::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Entity_Image_descriptor_;
}

const Entity_Image& Entity_Image::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_entity_2eproto();
  return *default_instance_;
}

Entity_Image* Entity_Image::default_instance_ = NULL;

Entity_Image* Entity_Image::New() const {
  return new Entity_Image;
}

void Entity_Image::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Entity_Image*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(width_, height_);
    if (has_rgbpixelsize()) {
      if (rgbpixelsize_ != NULL) rgbpixelsize_->::personalRobotics::Point2D::Clear();
    }
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        data_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Entity_Image::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:procamPRL.Entity.Image)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 width = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_height;
        break;
      }

      // optional int32 height = 2;
      case 2: {
        if (tag == 16) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_rgbPixelSize;
        break;
      }

      // optional .personalRobotics.Point2D rgbPixelSize = 3;
      case 3: {
        if (tag == 26) {
         parse_rgbPixelSize:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgbpixelsize()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_data;
        break;
      }

      // optional bytes data = 4;
      case 4: {
        if (tag == 34) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:procamPRL.Entity.Image)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:procamPRL.Entity.Image)
  return false;
#undef DO_
}

void Entity_Image::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:procamPRL.Entity.Image)
  // optional int32 width = 1;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->width(), output);
  }

  // optional int32 height = 2;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->height(), output);
  }

  // optional .personalRobotics.Point2D rgbPixelSize = 3;
  if (has_rgbpixelsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->rgbpixelsize(), output);
  }

  // optional bytes data = 4;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:procamPRL.Entity.Image)
}

::google::protobuf::uint8* Entity_Image::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:procamPRL.Entity.Image)
  // optional int32 width = 1;
  if (has_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->width(), target);
  }

  // optional int32 height = 2;
  if (has_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->height(), target);
  }

  // optional .personalRobotics.Point2D rgbPixelSize = 3;
  if (has_rgbpixelsize()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->rgbpixelsize(), target);
  }

  // optional bytes data = 4;
  if (has_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:procamPRL.Entity.Image)
  return target;
}

int Entity_Image::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 width = 1;
    if (has_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->width());
    }

    // optional int32 height = 2;
    if (has_height()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->height());
    }

    // optional .personalRobotics.Point2D rgbPixelSize = 3;
    if (has_rgbpixelsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->rgbpixelsize());
    }

    // optional bytes data = 4;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Entity_Image::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Entity_Image* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Entity_Image*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Entity_Image::MergeFrom(const Entity_Image& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
    if (from.has_rgbpixelsize()) {
      mutable_rgbpixelsize()->::personalRobotics::Point2D::MergeFrom(from.rgbpixelsize());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Entity_Image::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Entity_Image::CopyFrom(const Entity_Image& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Entity_Image::IsInitialized() const {

  if (has_rgbpixelsize()) {
    if (!this->rgbpixelsize().IsInitialized()) return false;
  }
  return true;
}

void Entity_Image::Swap(Entity_Image* other) {
  if (other != this) {
    std::swap(width_, other->width_);
    std::swap(height_, other->height_);
    std::swap(rgbpixelsize_, other->rgbpixelsize_);
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Entity_Image::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Entity_Image_descriptor_;
  metadata.reflection = Entity_Image_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Entity::kPoseFieldNumber;
const int Entity::kBoundingSizeFieldNumber;
const int Entity::kIdFieldNumber;
const int Entity::kContoursFieldNumber;
const int Entity::kProjPixelSizeFieldNumber;
const int Entity::kImageFieldNumber;
#endif  // !_MSC_VER

Entity::Entity()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:procamPRL.Entity)
}

void Entity::InitAsDefaultInstance() {
  pose_ = const_cast< ::personalRobotics::Pose2D*>(&::personalRobotics::Pose2D::default_instance());
  boundingsize_ = const_cast< ::personalRobotics::Point2D*>(&::personalRobotics::Point2D::default_instance());
  projpixelsize_ = const_cast< ::personalRobotics::Point2D*>(&::personalRobotics::Point2D::default_instance());
  image_ = const_cast< ::procamPRL::Entity_Image*>(&::procamPRL::Entity_Image::default_instance());
}

Entity::Entity(const Entity& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:procamPRL.Entity)
}

void Entity::SharedCtor() {
  _cached_size_ = 0;
  pose_ = NULL;
  boundingsize_ = NULL;
  id_ = 0;
  projpixelsize_ = NULL;
  image_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Entity::~Entity() {
  // @@protoc_insertion_point(destructor:procamPRL.Entity)
  SharedDtor();
}

void Entity::SharedDtor() {
  if (this != default_instance_) {
    delete pose_;
    delete boundingsize_;
    delete projpixelsize_;
    delete image_;
  }
}

void Entity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Entity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Entity_descriptor_;
}

const Entity& Entity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_entity_2eproto();
  return *default_instance_;
}

Entity* Entity::default_instance_ = NULL;

Entity* Entity::New() const {
  return new Entity;
}

void Entity::Clear() {
  if (_has_bits_[0 / 32] & 55) {
    if (has_pose()) {
      if (pose_ != NULL) pose_->::personalRobotics::Pose2D::Clear();
    }
    if (has_boundingsize()) {
      if (boundingsize_ != NULL) boundingsize_->::personalRobotics::Point2D::Clear();
    }
    id_ = 0;
    if (has_projpixelsize()) {
      if (projpixelsize_ != NULL) projpixelsize_->::personalRobotics::Point2D::Clear();
    }
    if (has_image()) {
      if (image_ != NULL) image_->::procamPRL::Entity_Image::Clear();
    }
  }
  contours_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Entity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:procamPRL.Entity)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .personalRobotics.Pose2D pose = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pose()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_boundingSize;
        break;
      }

      // optional .personalRobotics.Point2D boundingSize = 2;
      case 2: {
        if (tag == 18) {
         parse_boundingSize:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_boundingsize()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_id;
        break;
      }

      // optional int32 id = 3;
      case 3: {
        if (tag == 24) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_contours;
        break;
      }

      // repeated .personalRobotics.Point2D contours = 4;
      case 4: {
        if (tag == 34) {
         parse_contours:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_contours()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_contours;
        if (input->ExpectTag(42)) goto parse_projPixelSize;
        break;
      }

      // optional .personalRobotics.Point2D projPixelSize = 5;
      case 5: {
        if (tag == 42) {
         parse_projPixelSize:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_projpixelsize()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_image;
        break;
      }

      // optional .procamPRL.Entity.Image image = 6;
      case 6: {
        if (tag == 50) {
         parse_image:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_image()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:procamPRL.Entity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:procamPRL.Entity)
  return false;
#undef DO_
}

void Entity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:procamPRL.Entity)
  // optional .personalRobotics.Pose2D pose = 1;
  if (has_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->pose(), output);
  }

  // optional .personalRobotics.Point2D boundingSize = 2;
  if (has_boundingsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->boundingsize(), output);
  }

  // optional int32 id = 3;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->id(), output);
  }

  // repeated .personalRobotics.Point2D contours = 4;
  for (int i = 0; i < this->contours_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->contours(i), output);
  }

  // optional .personalRobotics.Point2D projPixelSize = 5;
  if (has_projpixelsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->projpixelsize(), output);
  }

  // optional .procamPRL.Entity.Image image = 6;
  if (has_image()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->image(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:procamPRL.Entity)
}

::google::protobuf::uint8* Entity::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:procamPRL.Entity)
  // optional .personalRobotics.Pose2D pose = 1;
  if (has_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->pose(), target);
  }

  // optional .personalRobotics.Point2D boundingSize = 2;
  if (has_boundingsize()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->boundingsize(), target);
  }

  // optional int32 id = 3;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->id(), target);
  }

  // repeated .personalRobotics.Point2D contours = 4;
  for (int i = 0; i < this->contours_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->contours(i), target);
  }

  // optional .personalRobotics.Point2D projPixelSize = 5;
  if (has_projpixelsize()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->projpixelsize(), target);
  }

  // optional .procamPRL.Entity.Image image = 6;
  if (has_image()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->image(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:procamPRL.Entity)
  return target;
}

int Entity::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .personalRobotics.Pose2D pose = 1;
    if (has_pose()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->pose());
    }

    // optional .personalRobotics.Point2D boundingSize = 2;
    if (has_boundingsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->boundingsize());
    }

    // optional int32 id = 3;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional .personalRobotics.Point2D projPixelSize = 5;
    if (has_projpixelsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->projpixelsize());
    }

    // optional .procamPRL.Entity.Image image = 6;
    if (has_image()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->image());
    }

  }
  // repeated .personalRobotics.Point2D contours = 4;
  total_size += 1 * this->contours_size();
  for (int i = 0; i < this->contours_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->contours(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Entity::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Entity* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Entity*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Entity::MergeFrom(const Entity& from) {
  GOOGLE_CHECK_NE(&from, this);
  contours_.MergeFrom(from.contours_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_pose()) {
      mutable_pose()->::personalRobotics::Pose2D::MergeFrom(from.pose());
    }
    if (from.has_boundingsize()) {
      mutable_boundingsize()->::personalRobotics::Point2D::MergeFrom(from.boundingsize());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_projpixelsize()) {
      mutable_projpixelsize()->::personalRobotics::Point2D::MergeFrom(from.projpixelsize());
    }
    if (from.has_image()) {
      mutable_image()->::procamPRL::Entity_Image::MergeFrom(from.image());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Entity::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Entity::CopyFrom(const Entity& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Entity::IsInitialized() const {

  if (has_pose()) {
    if (!this->pose().IsInitialized()) return false;
  }
  if (has_boundingsize()) {
    if (!this->boundingsize().IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->contours())) return false;
  if (has_projpixelsize()) {
    if (!this->projpixelsize().IsInitialized()) return false;
  }
  if (has_image()) {
    if (!this->image().IsInitialized()) return false;
  }
  return true;
}

void Entity::Swap(Entity* other) {
  if (other != this) {
    std::swap(pose_, other->pose_);
    std::swap(boundingsize_, other->boundingsize_);
    std::swap(id_, other->id_);
    contours_.Swap(&other->contours_);
    std::swap(projpixelsize_, other->projpixelsize_);
    std::swap(image_, other->image_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Entity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Entity_descriptor_;
  metadata.reflection = Entity_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* EntityList_Command_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EntityList_Command_descriptor_;
}
bool EntityList_Command_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const EntityList_Command EntityList::NONE;
const EntityList_Command EntityList::SEND_DISPLAY_INFO_PACKET;
const EntityList_Command EntityList::START_CALIBRATION;
const EntityList_Command EntityList::CALIBRATION_COMPLETE;
const EntityList_Command EntityList::START_STREAM;
const EntityList_Command EntityList::STOP_STREAM;
const EntityList_Command EntityList::DISCONNECT;
const EntityList_Command EntityList::Command_MIN;
const EntityList_Command EntityList::Command_MAX;
const int EntityList::Command_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int EntityList::kTimestampFieldNumber;
const int EntityList::kFrameIdFieldNumber;
const int EntityList::kCommandFieldNumber;
const int EntityList::kEntityListFieldNumber;
#endif  // !_MSC_VER

EntityList::EntityList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:procamPRL.EntityList)
}

void EntityList::InitAsDefaultInstance() {
}

EntityList::EntityList(const EntityList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:procamPRL.EntityList)
}

void EntityList::SharedCtor() {
  _cached_size_ = 0;
  timestamp_ = 0;
  frameid_ = 0;
  command_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

EntityList::~EntityList() {
  // @@protoc_insertion_point(destructor:procamPRL.EntityList)
  SharedDtor();
}

void EntityList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void EntityList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EntityList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EntityList_descriptor_;
}

const EntityList& EntityList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_entity_2eproto();
  return *default_instance_;
}

EntityList* EntityList::default_instance_ = NULL;

EntityList* EntityList::New() const {
  return new EntityList;
}

void EntityList::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<EntityList*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(timestamp_, frameid_);
    command_ = 1;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  entitylist_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool EntityList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:procamPRL.EntityList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double timestamp = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_frameId;
        break;
      }

      // optional int32 frameId = 2;
      case 2: {
        if (tag == 16) {
         parse_frameId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frameid_)));
          set_has_frameid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_command;
        break;
      }

      // optional .procamPRL.EntityList.Command command = 5 [default = NONE];
      case 5: {
        if (tag == 40) {
         parse_command:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::procamPRL::EntityList_Command_IsValid(value)) {
            set_command(static_cast< ::procamPRL::EntityList_Command >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_entityList;
        break;
      }

      // repeated .procamPRL.Entity entityList = 6;
      case 6: {
        if (tag == 50) {
         parse_entityList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_entitylist()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_entityList;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:procamPRL.EntityList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:procamPRL.EntityList)
  return false;
#undef DO_
}

void EntityList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:procamPRL.EntityList)
  // optional double timestamp = 1;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->timestamp(), output);
  }

  // optional int32 frameId = 2;
  if (has_frameid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->frameid(), output);
  }

  // optional .procamPRL.EntityList.Command command = 5 [default = NONE];
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->command(), output);
  }

  // repeated .procamPRL.Entity entityList = 6;
  for (int i = 0; i < this->entitylist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->entitylist(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:procamPRL.EntityList)
}

::google::protobuf::uint8* EntityList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:procamPRL.EntityList)
  // optional double timestamp = 1;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->timestamp(), target);
  }

  // optional int32 frameId = 2;
  if (has_frameid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->frameid(), target);
  }

  // optional .procamPRL.EntityList.Command command = 5 [default = NONE];
  if (has_command()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->command(), target);
  }

  // repeated .procamPRL.Entity entityList = 6;
  for (int i = 0; i < this->entitylist_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->entitylist(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:procamPRL.EntityList)
  return target;
}

int EntityList::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double timestamp = 1;
    if (has_timestamp()) {
      total_size += 1 + 8;
    }

    // optional int32 frameId = 2;
    if (has_frameid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->frameid());
    }

    // optional .procamPRL.EntityList.Command command = 5 [default = NONE];
    if (has_command()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->command());
    }

  }
  // repeated .procamPRL.Entity entityList = 6;
  total_size += 1 * this->entitylist_size();
  for (int i = 0; i < this->entitylist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->entitylist(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EntityList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const EntityList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const EntityList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void EntityList::MergeFrom(const EntityList& from) {
  GOOGLE_CHECK_NE(&from, this);
  entitylist_.MergeFrom(from.entitylist_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_frameid()) {
      set_frameid(from.frameid());
    }
    if (from.has_command()) {
      set_command(from.command());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void EntityList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EntityList::CopyFrom(const EntityList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EntityList::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->entitylist())) return false;
  return true;
}

void EntityList::Swap(EntityList* other) {
  if (other != this) {
    std::swap(timestamp_, other->timestamp_);
    std::swap(frameid_, other->frameid_);
    std::swap(command_, other->command_);
    entitylist_.Swap(&other->entitylist_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata EntityList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EntityList_descriptor_;
  metadata.reflection = EntityList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace procamPRL

// @@protoc_insertion_point(global_scope)
