// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose2D.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pose2D.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace personalRobotics {

namespace {

const ::google::protobuf::Descriptor* Pose2D_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Pose2D_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pose2D_2eproto() {
  protobuf_AddDesc_pose2D_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pose2D.proto");
  GOOGLE_CHECK(file != NULL);
  Pose2D_descriptor_ = file->message_type(0);
  static const int Pose2D_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose2D, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose2D, angle_),
  };
  Pose2D_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Pose2D_descriptor_,
      Pose2D::default_instance_,
      Pose2D_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose2D, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose2D, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Pose2D));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pose2D_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Pose2D_descriptor_, &Pose2D::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pose2D_2eproto() {
  delete Pose2D::default_instance_;
  delete Pose2D_reflection_;
}

void protobuf_AddDesc_pose2D_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::personalRobotics::protobuf_AddDesc_point2D_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014pose2D.proto\022\020personalRobotics\032\rpoint2"
    "D.proto\"G\n\006Pose2D\022+\n\010position\030\001 \002(\0132\031.pe"
    "rsonalRobotics.Point2D\022\020\n\005angle\030\002 \002(\002:\0010", 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pose2D.proto", &protobuf_RegisterTypes);
  Pose2D::default_instance_ = new Pose2D();
  Pose2D::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pose2D_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pose2D_2eproto {
  StaticDescriptorInitializer_pose2D_2eproto() {
    protobuf_AddDesc_pose2D_2eproto();
  }
} static_descriptor_initializer_pose2D_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Pose2D::kPositionFieldNumber;
const int Pose2D::kAngleFieldNumber;
#endif  // !_MSC_VER

Pose2D::Pose2D()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:personalRobotics.Pose2D)
}

void Pose2D::InitAsDefaultInstance() {
  position_ = const_cast< ::personalRobotics::Point2D*>(&::personalRobotics::Point2D::default_instance());
}

Pose2D::Pose2D(const Pose2D& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:personalRobotics.Pose2D)
}

void Pose2D::SharedCtor() {
  _cached_size_ = 0;
  position_ = NULL;
  angle_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Pose2D::~Pose2D() {
  // @@protoc_insertion_point(destructor:personalRobotics.Pose2D)
  SharedDtor();
}

void Pose2D::SharedDtor() {
  if (this != default_instance_) {
    delete position_;
  }
}

void Pose2D::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pose2D::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Pose2D_descriptor_;
}

const Pose2D& Pose2D::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pose2D_2eproto();
  return *default_instance_;
}

Pose2D* Pose2D::default_instance_ = NULL;

Pose2D* Pose2D::New() const {
  return new Pose2D;
}

void Pose2D::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_position()) {
      if (position_ != NULL) position_->::personalRobotics::Point2D::Clear();
    }
    angle_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Pose2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:personalRobotics.Pose2D)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .personalRobotics.Point2D position = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_angle;
        break;
      }

      // required float angle = 2 [default = 0];
      case 2: {
        if (tag == 21) {
         parse_angle:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &angle_)));
          set_has_angle();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:personalRobotics.Pose2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:personalRobotics.Pose2D)
  return false;
#undef DO_
}

void Pose2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:personalRobotics.Pose2D)
  // required .personalRobotics.Point2D position = 1;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->position(), output);
  }

  // required float angle = 2 [default = 0];
  if (has_angle()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->angle(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:personalRobotics.Pose2D)
}

::google::protobuf::uint8* Pose2D::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:personalRobotics.Pose2D)
  // required .personalRobotics.Point2D position = 1;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->position(), target);
  }

  // required float angle = 2 [default = 0];
  if (has_angle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->angle(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:personalRobotics.Pose2D)
  return target;
}

int Pose2D::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .personalRobotics.Point2D position = 1;
    if (has_position()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->position());
    }

    // required float angle = 2 [default = 0];
    if (has_angle()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pose2D::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Pose2D* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Pose2D*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Pose2D::MergeFrom(const Pose2D& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_position()) {
      mutable_position()->::personalRobotics::Point2D::MergeFrom(from.position());
    }
    if (from.has_angle()) {
      set_angle(from.angle());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Pose2D::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pose2D::CopyFrom(const Pose2D& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pose2D::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_position()) {
    if (!this->position().IsInitialized()) return false;
  }
  return true;
}

void Pose2D::Swap(Pose2D* other) {
  if (other != this) {
    std::swap(position_, other->position_);
    std::swap(angle_, other->angle_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Pose2D::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Pose2D_descriptor_;
  metadata.reflection = Pose2D_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace personalRobotics

// @@protoc_insertion_point(global_scope)
